quick.db support
MrAugu/discord-xp pull request #35
Opened 2021-04-13 10:42 UTC by Dragonizedpizza

2021-04-13 10:42 UTC, Dragonizedpizza commented
this is a work in progress

2021-04-13 11:13 UTC, Dragonizedpizza commented
I was thinking of something like:
```js
let DiscordXp;
If (DBName === 'quick.db') DiscordXp = require('./quick.db.js')
else if (DBName === 'mongoose') DiscordXp = require('./mongoose.js')
module.exports = DiscordXp;
```
And quick.db.js and mongoose's contents being something like:
```js
static async createUser() {
// contents for each db
}
```

2021-04-13 11:15 UTC, MrAugu requested changes
The master branch will be deprecated soon. We began the works for the rewrite, you can check the progress in the `rewrite`. You can create a quicker provider for the rewrite instead.

2021-04-13 12:00 UTC, Myst82015 commented
As MrAugu said. Check out the development branch and create a provider similar like the one from json or mongoose.

2021-04-23 13:35 UTC, Myst82015 commented
Since you didn't follow the format of a proper database provider and we didn't hear anything from you so far I'll close this pull request for now.

2021-04-23 13:35 UTC, closed without merging